# This is a basic workflow to help you get started with Actions

name: Run Cross Platform Test

# Controls when the workflow will run
on: [push]

defaults:
  run:
    shell: pwsh

jobs:
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

